name: Back-end_Projet-docker

services:
  database:
    image: esgi-postgres
    container_name: postgres
    tty: true
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: esgi
      POSTGRES_DB: esgi
    networks:
      - bridge

  adminer:
    image: esgi-adminer
    container_name: adminer
    ports:
      - 8080:80
    depends_on:
      - database

volumes:
  database:

networks:
  bridge:
    name: bridge
    external: true