FROM alpine

RUN apk --update add wget \
                     php \
                     php-fpm \
                     php-phar \
                     php-iconv \
                     php-mbstring \
                     php-openssl 


RUN wget -P /tmp/ https://getcomposer.org/installer
RUN php /tmp/installer --install-dir=/usr/local/bin --filename=composer
RUN rm -r /tmp/*