FROM alpine

ENV SYMFONY_PROJECT_NAME "esgi"
ENV DATABASE_URL "postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=16&charset=utf8"

RUN apk --update add wget pcre curl

COPY entrypoint-symfony.sh /docker-entrypoint.sh

COPY CaddyFile /etc/caddy/CaddyFile

RUN chmod +x /docker-entrypoint.sh

EXPOSE 8001
EXPOSE 2019

ENTRYPOINT [ "/docker-entrypoint.sh" ]