services:
  composer:
    image: esgi-composer
    container_name: composer
    tty: true
    volumes:
      - composerFiles:/usr/local/bin
      - phpFile:/usr/bin/
      - phpExtensions:/usr/lib/
      - phpExtensions2:/etc/php82/
      - phpfpmExtension:/usr/sbin
  
  symfony:
    image: esgi-symfony
    container_name: symfony
    tty: true
    volumes:
      - composerFiles:/usr/local/bin
      - phpFile:/usr/bin/
      - phpExtensions:/usr/lib/
      - phpExtensions2:/etc/php82/
      - phpfpmExtension:/usr/sbin
      - ./symfony/:/home/
    environment:
      SYMFONY_PROJECT_NAME: projet-docker
      DATABASE_URL: "postgresql://esgi:esgi@localhost:5432/esgi?serverVersion=16&charset=utf8"
    ports:
      - 8000:80
    depends_on:
      - composer

volumes:
  composerFiles:
  phpFile:
  phpExtensions:
  phpExtensions2:
  phpfpmExtension: